"""TensorRT builder placeholder."""

from __future__ import annotations

from pathlib import Path

from inferedgeforge.builders.base import BaseBuilder, BuildRequest, BuildResult


class TensorRTBuilder(BaseBuilder):
    backend_name = "tensorrt"

    def build(self, request: BuildRequest) -> BuildResult:
        output_dir = Path(request.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        artifact_path = output_dir / "model.engine"
        artifact_path.write_text(
            (
                "Placeholder deployment artifact generated by the "
                "InferEdgeForge MVP build flow.\n"
            ),
            encoding="utf-8",
        )

        return BuildResult(
            backend=self.backend_name,
            target=request.preset.target,
            artifact_paths=[str(artifact_path)],
        )
